const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const element = {addEventListener(){}, value:'', classList:{toggle(){}}};
const context = {document:{querySelector:()=>element,querySelectorAll:()=>[]},fetch:()=>new Promise(()=>{}), URL, Date, Intl, console};
vm.createContext(context);
vm.runInContext(fs.readFileSync('public/app.js','utf8')+'\nglobalThis.api={timeMatches,range,esc};',context);
const {timeMatches,range,esc}=context.api;
assert.equal(timeMatches('11am - 1pm','morning'),true);
assert.equal(timeMatches('11am - 1pm','afternoon'),true);
assert.equal(timeMatches('11am - 1pm','evening'),false);
assert.equal(timeMatches('6–8pm','evening'),true);
assert.equal(timeMatches('10am–noon','afternoon'),false);
assert.equal(timeMatches('Time not published — check event link','morning'),false);
assert.equal(timeMatches('Time not published — check event link','all'),true);
const [start,end]=range('month');
assert.ok(start.endsWith('-01'));
assert.ok(start<end);
assert.equal(esc('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;');
console.log('Time overlap, unknown times, date ranges, and text escaping passed.');
